/*
 * ChaosCore
 * Copyright (C) CraftationGaming <https://www.craftationgaming.com/>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package me.RockinChaos.core.utils.types;

import javax.annotation.Nullable;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

@SuppressWarnings("unused")
public enum TransformBlocks {
    DIRT("GRASS_BLOCK", "GRASS", "GRASS_PATH", "FARMLAND", "COARSE_DIRT", "PODZOL", "MYCELIUM"),
    GRASS_BLOCK("DIRT", "GRASS_PATH", "FARMLAND"),
    GRASS("DIRT", "GRASS_PATH", "FARMLAND"),
    FARMLAND("DIRT", "GRASS_BLOCK", "GRASS"),
    GRASS_PATH("DIRT", "GRASS_BLOCK", "GRASS"),
    PODZOL("DIRT"),
    MYCELIUM("DIRT"),

    // Log stripping
    OAK_LOG("STRIPPED_OAK_LOG"),
    STRIPPED_OAK_LOG("OAK_LOG"),
    SPRUCE_LOG("STRIPPED_SPRUCE_LOG"),
    STRIPPED_SPRUCE_LOG("SPRUCE_LOG"),
    BIRCH_LOG("STRIPPED_BIRCH_LOG"),
    STRIPPED_BIRCH_LOG("BIRCH_LOG"),
    JUNGLE_LOG("STRIPPED_JUNGLE_LOG"),
    STRIPPED_JUNGLE_LOG("JUNGLE_LOG"),
    ACACIA_LOG("STRIPPED_ACACIA_LOG"),
    STRIPPED_ACACIA_LOG("ACACIA_LOG"),
    DARK_OAK_LOG("STRIPPED_DARK_OAK_LOG"),
    STRIPPED_DARK_OAK_LOG("DARK_OAK_LOG"),
    MANGROVE_LOG("STRIPPED_MANGROVE_LOG"),
    STRIPPED_MANGROVE_LOG("MANGROVE_LOG"),
    CHERRY_LOG("STRIPPED_CHERRY_LOG"),
    STRIPPED_CHERRY_LOG("CHERRY_LOG"),
    CRIMSON_STEM("STRIPPED_CRIMSON_STEM"),
    STRIPPED_CRIMSON_STEM("CRIMSON_STEM"),
    WARPED_STEM("STRIPPED_WARPED_STEM"),
    STRIPPED_WARPED_STEM("WARPED_STEM"),

    // Wood stripping
    OAK_WOOD("STRIPPED_OAK_WOOD"),
    STRIPPED_OAK_WOOD("OAK_WOOD"),
    SPRUCE_WOOD("STRIPPED_SPRUCE_WOOD"),
    STRIPPED_SPRUCE_WOOD("SPRUCE_WOOD"),
    BIRCH_WOOD("STRIPPED_BIRCH_WOOD"),
    STRIPPED_BIRCH_WOOD("BIRCH_WOOD"),
    JUNGLE_WOOD("STRIPPED_JUNGLE_WOOD"),
    STRIPPED_JUNGLE_WOOD("JUNGLE_WOOD"),
    ACACIA_WOOD("STRIPPED_ACACIA_WOOD"),
    STRIPPED_ACACIA_WOOD("ACACIA_WOOD"),
    DARK_OAK_WOOD("STRIPPED_DARK_OAK_WOOD"),
    STRIPPED_DARK_OAK_WOOD("DARK_OAK_WOOD"),
    MANGROVE_WOOD("STRIPPED_MANGROVE_WOOD"),
    STRIPPED_MANGROVE_WOOD("MANGROVE_WOOD"),
    CHERRY_WOOD("STRIPPED_CHERRY_WOOD"),
    STRIPPED_CHERRY_WOOD("CHERRY_WOOD"),
    CRIMSON_HYPHAE("STRIPPED_CRIMSON_HYPHAE"),
    STRIPPED_CRIMSON_HYPHAE("CRIMSON_HYPHAE"),
    WARPED_HYPHAE("STRIPPED_WARPED_HYPHAE"),
    STRIPPED_WARPED_HYPHAE("WARPED_HYPHAE"),

    // Copper oxidation (all stages can transform to each other)
    COPPER_BLOCK("EXPOSED_COPPER", "WEATHERED_COPPER", "OXIDIZED_COPPER", "WAXED_COPPER_BLOCK"),
    EXPOSED_COPPER("COPPER_BLOCK", "WEATHERED_COPPER", "OXIDIZED_COPPER", "WAXED_EXPOSED_COPPER"),
    WEATHERED_COPPER("COPPER_BLOCK", "EXPOSED_COPPER", "OXIDIZED_COPPER", "WAXED_WEATHERED_COPPER"),
    OXIDIZED_COPPER("COPPER_BLOCK", "EXPOSED_COPPER", "WEATHERED_COPPER", "WAXED_OXIDIZED_COPPER"),
    WAXED_COPPER_BLOCK("COPPER_BLOCK", "WAXED_EXPOSED_COPPER", "WAXED_WEATHERED_COPPER", "WAXED_OXIDIZED_COPPER"),
    WAXED_EXPOSED_COPPER("EXPOSED_COPPER", "WAXED_COPPER_BLOCK", "WAXED_WEATHERED_COPPER", "WAXED_OXIDIZED_COPPER"),
    WAXED_WEATHERED_COPPER("WEATHERED_COPPER", "WAXED_COPPER_BLOCK", "WAXED_EXPOSED_COPPER", "WAXED_OXIDIZED_COPPER"),
    WAXED_OXIDIZED_COPPER("OXIDIZED_COPPER", "WAXED_COPPER_BLOCK", "WAXED_EXPOSED_COPPER", "WAXED_WEATHERED_COPPER"),

    CUT_COPPER("EXPOSED_CUT_COPPER", "WEATHERED_CUT_COPPER", "OXIDIZED_CUT_COPPER", "WAXED_CUT_COPPER"),
    EXPOSED_CUT_COPPER("CUT_COPPER", "WEATHERED_CUT_COPPER", "OXIDIZED_CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER"),
    WEATHERED_CUT_COPPER("CUT_COPPER", "EXPOSED_CUT_COPPER", "OXIDIZED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER"),
    OXIDIZED_CUT_COPPER("CUT_COPPER", "EXPOSED_CUT_COPPER", "WEATHERED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER"),
    WAXED_CUT_COPPER("CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER"),
    WAXED_EXPOSED_CUT_COPPER("EXPOSED_CUT_COPPER", "WAXED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER"),
    WAXED_WEATHERED_CUT_COPPER("WEATHERED_CUT_COPPER", "WAXED_CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER", "WAXED_OXIDIZED_CUT_COPPER"),
    WAXED_OXIDIZED_CUT_COPPER("OXIDIZED_CUT_COPPER", "WAXED_CUT_COPPER", "WAXED_EXPOSED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER"),

    CUT_COPPER_STAIRS("EXPOSED_CUT_COPPER_STAIRS", "WEATHERED_CUT_COPPER_STAIRS", "OXIDIZED_CUT_COPPER_STAIRS", "WAXED_CUT_COPPER_STAIRS"),
    EXPOSED_CUT_COPPER_STAIRS("CUT_COPPER_STAIRS", "WEATHERED_CUT_COPPER_STAIRS", "OXIDIZED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_CUT_COPPER_STAIRS"),
    WEATHERED_CUT_COPPER_STAIRS("CUT_COPPER_STAIRS", "EXPOSED_CUT_COPPER_STAIRS", "OXIDIZED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_CUT_COPPER_STAIRS"),
    OXIDIZED_CUT_COPPER_STAIRS("CUT_COPPER_STAIRS", "EXPOSED_CUT_COPPER_STAIRS", "WEATHERED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_CUT_COPPER_STAIRS"),
    WAXED_CUT_COPPER_STAIRS("CUT_COPPER_STAIRS", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_CUT_COPPER_STAIRS"),
    WAXED_EXPOSED_CUT_COPPER_STAIRS("EXPOSED_CUT_COPPER_STAIRS", "WAXED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_CUT_COPPER_STAIRS"),
    WAXED_WEATHERED_CUT_COPPER_STAIRS("WEATHERED_CUT_COPPER_STAIRS", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_OXIDIZED_CUT_COPPER_STAIRS"),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS("OXIDIZED_CUT_COPPER_STAIRS", "WAXED_CUT_COPPER_STAIRS", "WAXED_EXPOSED_CUT_COPPER_STAIRS", "WAXED_WEATHERED_CUT_COPPER_STAIRS"),

    CUT_COPPER_SLAB("EXPOSED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_SLAB"),
    EXPOSED_CUT_COPPER_SLAB("CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_SLAB"),
    WEATHERED_CUT_COPPER_SLAB("CUT_COPPER_SLAB", "EXPOSED_CUT_COPPER_SLAB", "OXIDIZED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_SLAB"),
    OXIDIZED_CUT_COPPER_SLAB("CUT_COPPER_SLAB", "EXPOSED_CUT_COPPER_SLAB", "WEATHERED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_SLAB"),
    WAXED_CUT_COPPER_SLAB("CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_SLAB"),
    WAXED_EXPOSED_CUT_COPPER_SLAB("EXPOSED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_SLAB"),
    WAXED_WEATHERED_CUT_COPPER_SLAB("WEATHERED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_OXIDIZED_CUT_COPPER_SLAB"),
    WAXED_OXIDIZED_CUT_COPPER_SLAB("OXIDIZED_CUT_COPPER_SLAB", "WAXED_CUT_COPPER_SLAB", "WAXED_EXPOSED_CUT_COPPER_SLAB", "WAXED_WEATHERED_CUT_COPPER_SLAB"),

    // Concrete powder to concrete
    WHITE_CONCRETE_POWDER("WHITE_CONCRETE"),
    ORANGE_CONCRETE_POWDER("ORANGE_CONCRETE"),
    MAGENTA_CONCRETE_POWDER("MAGENTA_CONCRETE"),
    LIGHT_BLUE_CONCRETE_POWDER("LIGHT_BLUE_CONCRETE"),
    YELLOW_CONCRETE_POWDER("YELLOW_CONCRETE"),
    LIME_CONCRETE_POWDER("LIME_CONCRETE"),
    PINK_CONCRETE_POWDER("PINK_CONCRETE"),
    GRAY_CONCRETE_POWDER("GRAY_CONCRETE"),
    LIGHT_GRAY_CONCRETE_POWDER("LIGHT_GRAY_CONCRETE"),
    CYAN_CONCRETE_POWDER("CYAN_CONCRETE"),
    PURPLE_CONCRETE_POWDER("PURPLE_CONCRETE"),
    BLUE_CONCRETE_POWDER("BLUE_CONCRETE"),
    BROWN_CONCRETE_POWDER("BROWN_CONCRETE"),
    GREEN_CONCRETE_POWDER("GREEN_CONCRETE"),
    RED_CONCRETE_POWDER("RED_CONCRETE"),
    BLACK_CONCRETE_POWDER("BLACK_CONCRETE"),

    // Sponge
    SPONGE("WET_SPONGE"),
    WET_SPONGE("SPONGE"),

    // Coral death/revival
    TUBE_CORAL_BLOCK("DEAD_TUBE_CORAL_BLOCK"),
    DEAD_TUBE_CORAL_BLOCK("TUBE_CORAL_BLOCK"),
    BRAIN_CORAL_BLOCK("DEAD_BRAIN_CORAL_BLOCK"),
    DEAD_BRAIN_CORAL_BLOCK("BRAIN_CORAL_BLOCK"),
    BUBBLE_CORAL_BLOCK("DEAD_BUBBLE_CORAL_BLOCK"),
    DEAD_BUBBLE_CORAL_BLOCK("BUBBLE_CORAL_BLOCK"),
    FIRE_CORAL_BLOCK("DEAD_FIRE_CORAL_BLOCK"),
    DEAD_FIRE_CORAL_BLOCK("FIRE_CORAL_BLOCK"),
    HORN_CORAL_BLOCK("DEAD_HORN_CORAL_BLOCK"),
    DEAD_HORN_CORAL_BLOCK("HORN_CORAL_BLOCK"),
    TUBE_CORAL("DEAD_TUBE_CORAL"),
    DEAD_TUBE_CORAL("TUBE_CORAL"),
    BRAIN_CORAL("DEAD_BRAIN_CORAL"),
    DEAD_BRAIN_CORAL("BRAIN_CORAL"),
    BUBBLE_CORAL("DEAD_BUBBLE_CORAL"),
    DEAD_BUBBLE_CORAL("BUBBLE_CORAL"),
    FIRE_CORAL("DEAD_FIRE_CORAL"),
    DEAD_FIRE_CORAL("FIRE_CORAL"),
    HORN_CORAL("DEAD_HORN_CORAL"),
    DEAD_HORN_CORAL("HORN_CORAL"),
    TUBE_CORAL_FAN("DEAD_TUBE_CORAL_FAN"),
    DEAD_TUBE_CORAL_FAN("TUBE_CORAL_FAN"),
    BRAIN_CORAL_FAN("DEAD_BRAIN_CORAL_FAN"),
    DEAD_BRAIN_CORAL_FAN("BRAIN_CORAL_FAN"),
    BUBBLE_CORAL_FAN("DEAD_BUBBLE_CORAL_FAN"),
    DEAD_BUBBLE_CORAL_FAN("BUBBLE_CORAL_FAN"),
    FIRE_CORAL_FAN("DEAD_FIRE_CORAL_FAN"),
    DEAD_FIRE_CORAL_FAN("FIRE_CORAL_FAN"),
    HORN_CORAL_FAN("DEAD_HORN_CORAL_FAN"),
    DEAD_HORN_CORAL_FAN("HORN_CORAL_FAN"),

    // Ice melting
    ICE("WATER", "FLOWING_WATER"),
    FROSTED_ICE("WATER", "FLOWING_WATER"),
    PACKED_ICE("WATER", "FLOWING_WATER"),

    // Bamboo growth
    BAMBOO_SAPLING("BAMBOO"),

    // Mushroom blocks
    BROWN_MUSHROOM_BLOCK("MUSHROOM_STEM"),
    RED_MUSHROOM_BLOCK("MUSHROOM_STEM"),
    MUSHROOM_STEM("BROWN_MUSHROOM_BLOCK", "RED_MUSHROOM_BLOCK");

    private final Set<String> allowedTransformations;

    TransformBlocks(String... allowedTransformations) {
        this.allowedTransformations = new HashSet<>(Arrays.asList(allowedTransformations));
    }

    /**
     * Checks if a block material transformation is valid/allowed.
     * Valid transformations include natural changes (dirt to grass), player interactions (log stripping),
     * and environmental effects (ice melting, copper oxidation).
     *
     * @param originalMaterial - The original material that was placed.
     * @param currentMaterial - The current material to validate against.
     * @return True if the transformation is allowed, false otherwise.
     */
    public static boolean isTransformation(final @Nullable String originalMaterial, final @Nullable String currentMaterial) {
        if (originalMaterial == null || originalMaterial.isEmpty() || currentMaterial == null || currentMaterial.isEmpty()) return false;
        if (originalMaterial.equals(currentMaterial)) return true;
        try {
            TransformBlocks transformation = TransformBlocks.valueOf(originalMaterial);
            return transformation.allowedTransformations.contains(currentMaterial);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }
}